services:
  web:
    build:
      context: .
    image: hillel_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
  migrate:
    depends_on:
      - db
    image: hillel_django
    volumes:
      - .:/app
    env_file: .env
    command: python manage.py migrate
    restart: on-failure
  redis:
    image: redis
    ports:
      - "63799:6379"
  celery:
    depends_on:
      - db
      - redis
    image: hillel_django
    volumes:
      - .:/app
    env_file: .env
    command: celery -A hillel_django worker -l info --beat
    restart: always
  db:
    image: postgres
    ports:
      # 54322 is the port on the host machine
      # 5432 is the port on the container
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
